sudo: required

services:
  - docker

before_install:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - docker build -t test/planet-sympy .
  - docker ps -a

script:
  - bin/test_travis.sh

env:
  global:
    secure: "hURQrkeWIjyHd613ffue25KauJPnTxIxdo41zWteiHVblkPB3EW+YxBUpd9Wh58BctmDzkMPDvoKGHa2WAh90FPDXWdeZM6rO8C65cPcVb9yBSpwAmkS98OOVeCsAVeCA+rZu/kMyFhbY1a6ujoVYVX4Hnz4KyzWdS6mctV3mfriv6B4Dmib8vRVwWqq6KiA/raOQKo8GvNt2Vuzgozc3gFPWI1RBx3FzsxzG7+WlLC8I4U3TEsnU0WlVbkU7Yoluxc39OEpmPvRg0rTBcnbuHvKcZYTZWbE7/enDxSWw85GJNpvlU1kKFyj4FBMXVKZCKSIO7jqCAJ9WiXKQWtrAhtZ4jvR0IAC75CB62eo5u93G56D9gPBL1pRKQkHdko3dPJpy4+Anw9XLiJt9vo7sxrdEKJv2lXJzP6G1kBlk4ayZRWDZy4BFAfvOX9jpJ7F/gYPSb7sNfOnZ8TJ7sNu5DBV5umB10GogXcpvQ901+oxBCzg7ipRaagRZqycML8taEhdSPoPUbUv36yn5/u5g0TrDuPopiwskMDIR3qohBcDb0HBBVGIzL5yf4qKRRvJDc+rQyLsA9xNw+Za1frgRFriyptuxmoiEetLPQYhY3Gz23o+5WzTv2JlTQHtJUEwsr2P2SW1kxwAKFQdGO5OLsoKtrAQERsom1H6VJ+iNrM="

notifications:
  email: false
