feeds:
  - url: http://sumith1896.github.io/feeds/feed.sympy.xml
    name: Sumith (sumith1896)
    face: sumith1896.png

  - url: https://www.asmeurer.com/blog/rss.xml
    name: Aaron Meurer (asmeurer)
    face: asmeurer.jpg

  - url: http://isuruf.blogspot.com/feeds/posts/default
    name: Isuru Fernando (isuruf)
    face: isuruf.jpg

  - url: http://iamit.in/blog/feeds/sympy.xml
    name: Amit Kumar (aktech)
    face: aktech.jpg

  - url: https://rajithsays.wordpress.com/category/symengine/feed/
    name: Rajith Vidanaarachchi (rajithv)
    face: rajithv.jpg

  - url: http://srajangarg.github.io/feed.xml
    name: Srajan Garg (srajangarg)
    face: srajangarg.jpg

  - url: https://shubhamtibra.wordpress.com/feed/
    name: Subham Tibra (shubhamtibra)
    face: shubham.jpg

  - url: http://shekharrajak.github.io/feed.xml
    name: Shekhar Prasad Rajak (shekharrajak)
    face: shekharrajak.jpg

  - url: https://gxyd.github.io/atom.xml
    name: Gaurav Dhingra (gxyd)
    face: gxyd.jpg

  - url: https://sampadblog.wordpress.com/feed/
    name: Sampad Saha (sampadsaha5)
    face: sampad.jpg

  - url: http://nishnik.github.io/feed.xml
    name: Nishant Nikhil (nishnik)
    face: nishnik.jpg

  - url: http://jbm950.github.io/feed.xml
    name: James Milam (jbm950)
    face: jbm950.jpg

  - url: https://kshitij10496.github.io/feed.xml
    name: Kshitij Saraogi(kshitij10496)
    face: kshitij10496.jpg

  - url: http://ravicharann.github.io/blog/feed.xml
    name: Ravicharan (RavicharanN)
    face: ravicharan.jpg

  - url: https://valglad.github.io/feed.xml
    name: Valeriia Gladkova (valglad)
    face: valglad.jpg

  - url: http://ranjithkumar007.github.io/feed.xml
    name: Ranjith Kumar (ranjithkumar007)
    face: ranjithkumar007.png

  - url: https://parsoyaarihant.github.io/blog/feed.xml
    name: Arihant Parsoya (parsoyaarihant)
    face: parsoyaarihant.jpeg

  - url: https://bjodah.github.io/blog/rss.xml
    name: Bj√∂rn Dahlgren (bjodah)
    face: bjodah.jpg

  - url: https://nesar2017.wordpress.com/feed/
    name: Abdullah Javed Nesar (Abdullahjavednesar)
    face: Abdullahjavednesar.jpg

  - url: https://szymag.github.io/feed.xml
    name: Szymon Mieszczak (szymag)
    face: szymag.jpg

  - url: http://sidhantnagpal.github.io/rss-gsoc.xml
    name: Sidhant Nagpal (sidhantnagpal)
    face: sidhantnagpal.jpg

  - url: http://yathartha22.github.io/feed.sympy.xml
    name: Yathartha Joshi (Yathartha22)
    face: yathartha.jpg

  - url: https://singhjashan.wordpress.com/feed
    name: Jashanpreet Singh Sraw (jashan498)
    face: jashan498.jpg

  - url: http://ashishkg0022.blogspot.in/feeds/posts/default?alt=rss
    name: Ashish Kumar Gaurav (ashishkg0022)
    face: ashishkg0022.jpg

  - url: https://nkhlpappu.wordpress.com/tag/sympy/feed
    name: Nikhil Pappu (NikhilPappu)
    face: NikhilPappu.jpeg

  - url: https://arighnaiitg.github.io/feed.xml
    name: Arighna Chakrabarty (arighnaiitg)
    face: Arighna.jpg

  - url: http://jmig5776.github.io/feed.sympy.xml
    name: Jogi Miglani (jmig5776)
    face: jmig5776.jpg

  - url: http://shubhamkjha.github.io/sympy_feed.xml
    name: Shubham Kumar Jha (ShubhamKJha)
    face: shubhamkjha.jpg

  - url: https://ishanaj.wordpress.com/category/sympy/feed/
    name: Ishan Joshi (ishanaj)
    face: ishanaj.jpg

  - url: http://divyanshu132.github.io/feed.sympy.xml
    name: Divyanshu Thakur (divyanshu132)
    face: divyanshu132.jpg

  - url: http://ritesh99rakesh.github.io/feed.xml
    name: Ritesh Kumar (ritesh99rakesh)
    face: ritesh99rakesh.jpg

  - url: https://anpandey.github.io/atom-sympy.xml
    name: Ankit Pandey (anpandey)
    face: anpandey.jpg

  - url: https://www.kangzhiq.com/tag/sympy/feed/
    name: Zhiqi KANG (kangzhiq)
    face: kangzhiq.jpg

  - url: https://sc0rpi0n101.github.io/categories/gsoc/index.xml
    name: Nikhil Maan (Sc0rpi0n101)
    face: Nikhil_Maan.jpg

  - url: https://smit-create.github.io/feed.xml
    name: Smit Lunagariya (Smit-create)
    face: Smitlunagariya.jpg

  - url: https://namannimmo10.github.io/emerald/atom.xml
    name: Naman Gera (namannimmo10)
    face: namannimmo10.jpg

  - url: https://sachin-4099.github.io/feed.sympy.xml
    name: Sachin Agarwal (sachin-4099)
    face: sachin-4099.jpg

  - url: https://friyaz.github.io/feed.sympy.xml
    name: Faisal Riyaz (friyaz)
    face: friyaz.jpg

  - url: http://abhinav28071999.github.io/feed.xml
    name: Abhinav Anand (abhinav28071999)
    face: abhinav28071999.jpg

  - url: https:///mijo2.github.io/feed.xml
    name: Milan Jolly (mijo2)
    face: mijo2.jpg

  - url: https://medium.com/feed/@mohitbalwani.ict17
    name: Mohit Balwani (Mohitbalwani26)
    face: Mohitbalwani26.jpg

  - url: https://tjstienstra.github.io/feed.xml
    name: Timo Stienstra (TJStienstra)
    face: tjstienstra.jpg

  - url: https://krishnavbajoria02.github.io/blog-sympy-gsoc2025/feed.xml
    name: Krishnav Bajoria (@krishnavbajoria02)
    face: krishnavbajoria02.jpg

  - url: https://leomanga.github.io/sympy-feed.xml
    name: Leonardo Mangani (leomanga)
    face: leomanga.jpg

  - url: https://rushabhmehta2005.github.io/feed.xml
    name: Rushabh Mehta (RushabhMehta2005)
    face: RushabhMehta2005.jpg
